### ISSUE TITLE
Could not find th 'dankeboy36.vscode-arduino-api' extension must be installed.

### ISSUE THREAD

**Issue by fubax** [dankeboy36/esp-exception-decoder#19]
I have currently installed the 'esp-exception-decoder' on Arduino 2.0.4. When running the IDE, I encounter the following error: 'Could not find the 'dankeboy36.vscode-arduino-api' extension. It must be installed.' 

Additionally, when I type 'ESP Exception Decoder: Show Decoder Terminal' in the Command Palette, nothing happens
please help

**Comment by dankeboy36** [comment]
Thank you for trying the decoder extension.

> on Arduino 2.0.4.

To use this feature, you need a more recent version of the Arduino IDE, at least `2.2.0`. You can download the latest version from https://www.arduino.cc/en/software. `2.3.2` is the latest as of writing.

https://github.com/arduino/arduino-ide/pull/2110 has been available since [Arduino IDE 2.2.0](https://github.com/arduino/arduino-ide/releases/tag/2.2.0).

I am closing this ticket, but please feel free to ask for help. You can also use the official Arduino forum: https://forum.arduino.cc/c/software/ide-2-x/93.
